name: Commit baby

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6,0'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node NeverGonnaNotCommit.js > README.md
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: TacticsCH
          author_email: alexandre.javet@hotmail.com
          force: false
          signoff: false
          message: 'README updated by GitHub Actions'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
